# Generated by Django 6.0.4 on 2026-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('name_fr', models.CharField(max_length=80, null=True, verbose_name='Nom')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('excerpt', models.TextField(help_text="1 ou 2 phrases qui résument l'article.", verbose_name='Extrait')),
                ('excerpt_fr', models.TextField(help_text="1 ou 2 phrases qui résument l'article.", null=True, verbose_name='Extrait')),
                ('excerpt_en', models.TextField(help_text="1 ou 2 phrases qui résument l'article.", null=True, verbose_name='Extrait')),
                ('body_html', models.TextField(help_text="Contenu de l'article en HTML.", verbose_name='Corps HTML')),
                ('body_html_fr', models.TextField(help_text="Contenu de l'article en HTML.", null=True, verbose_name='Corps HTML')),
                ('body_html_en', models.TextField(help_text="Contenu de l'article en HTML.", null=True, verbose_name='Corps HTML')),
                ('cover', models.ImageField(blank=True, upload_to='blog/', verbose_name='Image de couverture')),
                ('cover_alt', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texte alternatif')),
                ('meta_description', models.CharField(blank=True, max_length=200, verbose_name='Meta description')),
                ('meta_description_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta description')),
                ('meta_description_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta description')),
                ('reading_time', models.PositiveSmallIntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('published_at', models.DateTimeField(verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_published'], name='blog_articl_publish_a599c8_idx')],
            },
        ),
    ]
