# Generated by Django 6.0.4 on 2026-05-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Entreprise')),
                ('service', models.CharField(choices=[('cyber', 'Cybersécurité'), ('web', 'Web & Apps'), ('ia', 'IA & Automatisation'), ('support', 'Support'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Service')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
