# Generated by Django 6.0.4 on 2026-05-04 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanQuota',
            fields=[
                ('ip_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_scan_at', models.DateTimeField()),
                ('scan_count_24h', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quota de scan',
                'verbose_name_plural': 'Quotas de scan',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253, verbose_name='Domaine')),
                ('status', models.CharField(choices=[('queued', "En file d'attente"), ('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], db_index=True, default='queued', max_length=10, verbose_name='Statut')),
                ('queued_at', models.DateTimeField(auto_now_add=True, verbose_name='Mis en file')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé')),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score global')),
                ('grade', models.CharField(blank=True, max_length=2, verbose_name='Grade')),
                ('summary', models.JSONField(default=dict, verbose_name='Résumé sévérités')),
                ('requested_ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('requested_email_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('locale', models.CharField(default='fr', max_length=5, verbose_name='Locale')),
                ('is_public', models.BooleanField(default=True, verbose_name='Rapport public')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['status', 'queued_at'], name='maketrust_s_status_b2852f_idx'), models.Index(fields=['domain', '-queued_at'], name='maketrust_s_domain_cb3d91_idx')],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=50, verbose_name='Module')),
                ('severity', models.CharField(choices=[('pass', 'OK'), ('info', 'Info'), ('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], db_index=True, max_length=10, verbose_name='Sévérité')),
                ('title_key', models.CharField(max_length=100, verbose_name='Titre (clé i18n)')),
                ('fix_key', models.CharField(blank=True, max_length=100, verbose_name='Correctif (clé i18n)')),
                ('finding', models.JSONField(default=dict, verbose_name='Données brutes')),
                ('evidence', models.TextField(blank=True, verbose_name='Preuve textuelle')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Durée (ms)')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='maketrust.scan')),
            ],
            options={
                'verbose_name': 'Vérification',
                'verbose_name_plural': 'Vérifications',
                'ordering': ['module', 'id'],
            },
        ),
    ]
