# Generated by Django 6.0.4 on 2026-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketrust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='requested_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
