# Generated by Django 6.0.4 on 2026-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketrust', '0002_scan_requested_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='preview_image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Aperçu'),
        ),
        migrations.AddField(
            model_name='scan',
            name='preview_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Titre de la page'),
        ),
    ]
