# Generated by Django 6.0.4 on 2026-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketrust', '0003_scan_preview_image_url_scan_preview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('queued', "En file d'attente"), ('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec'), ('aborted', 'Annulé')], db_index=True, default='queued', max_length=10, verbose_name='Statut'),
        ),
    ]
