# Generated by Django 6.0.4 on 2026-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketrust', '0004_scan_aborted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='extra_dkim_selectors',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sélecteurs DKIM additionnels'),
        ),
    ]
