# Generated by Django 6.0.4 on 2026-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketrust', '0005_scan_extra_dkim_selectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Démarrage planifié'),
        ),
    ]
