# Generated by Django 6.0.4 on 2026-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketrust', '0006_scan_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Coché automatiquement quand un admin connecté lance le scan.', verbose_name='Scan interne'),
        ),
    ]
