# Generated by Django 6.0.4 on 2026-05-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketrust', '0007_scan_is_internal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanQuota',
        ),
    ]
